# Generated by Django 6.0.1 on 2026-01-30 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_table_comment_alter_course_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='ouvert aux inscriptions'),
        ),
    ]
