# Generated by Django 6.0.1 on 2026-02-06 15:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='course',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='courses/lessons/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mkv'], message="cette extension n'est pas prise en charge. \nle fichier doit en format  .mp4, .webm ou .mkv.")]),
        ),
    ]
