# Generated by Django 6.0.1 on 2026-02-06 16:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_reservation_options_course_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='video_file',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to='courses/lessons/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mkv'], message="cette extension n'est pas prise en charge. \nle fichier doit en format  .mp4, .webm ou .mkv.")]),
        ),
    ]
